#!/usr/bin/env bash

set -o errexit

# The name of the file as it will appear in the Dropbox directory.
outfile=backup-"`date +%Y-%m-%d`".json


repodir=`dirname "$0"`

tempdir="$OPENSHIFT_DATA_DIR"
if [ "$tempdir" == "" ]; then
    tempdir="$repodir"/dictionary/fixtures
fi

config="$HOME"/.dropbox_uploader
if [ "$DROPBOX_OAUTH_ACCESS_TOKEN" != "" ]; then
    config="$tempdir"/.dropbox_uploader
    echo "OAUTH_ACCESS_TOKEN=${DROPBOX_OAUTH_ACCESS_TOKEN}" > "$config"
fi

fixture="$tempdir"/backup.json
"$repodir"/manage.py dumpdata dictionary > "$fixture"

"$repodir"/Dropbox-Uploader/dropbox_uploader.sh -f "$config" upload "$fixture" "$outfile"
