#!/usr/bin/env bash

set -o errexit

repodir=`dirname "$0"`
echo 'Verifying that we can list the contents of the backup directory...'
"$repodir"/Dropbox-Uploader/dropbox_uploader.sh list

source "$HOME"/.dropbox_uploader

heroku config:set DROPBOX_APPKEY="${APPKEY}" DROPBOX_APPSECRET="${APPSECRET}" \
            DROPBOX_ACCESS_LEVEL="${ACCESS_LEVEL}" \
            DROPBOX_OAUTH_ACCESS_TOKEN="${OAUTH_ACCESS_TOKEN}" \
            DROPBOX_OAUTH_ACCESS_TOKEN_SECRET="${OAUTH_ACCESS_TOKEN_SECRET}"
