# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-29 22:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0002_auto_20180629_1037'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntryExampleInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='EntryVarietyInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.CharField(blank=True, default=b'', help_text=b'Additional language variety details, e.g. city names, Northern/Southern for Kodiak, or specific speakers', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Example',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vernacular', models.TextField(help_text=b'Text in Alutiiq (or perhaps other focus languages in the future?)', verbose_name=b'Alutiiq')),
                ('english', models.TextField(help_text=b'Natural translation of the text into English', verbose_name=b'English')),
                ('source_info', models.CharField(blank=True, default=b'', help_text=b'Page numbers, file IDs, dates, or other specific information needed to find the word in the source.', max_length=200, verbose_name=b'source details')),
                ('source_link', models.URLField(blank=True, default=b'', help_text=b'A URL to link to the source. If not empty, this will turn the "source details" into a hyperlink.')),
            ],
        ),
        migrations.CreateModel(
            name='ExampleVarietyInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.CharField(blank=True, default=b'', help_text=b'Additional language variety details, e.g. city names, Northern/Southern for Kodiak, or specific speakers', max_length=200, verbose_name=b'details')),
                ('example', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.Example')),
            ],
        ),
        migrations.CreateModel(
            name='SeeAlso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Variety',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abbrev', models.CharField(max_length=100, unique=True, verbose_name=b'abbreviation')),
                ('description', models.CharField(max_length=1000)),
            ],
            options={
                'verbose_name_plural': 'varieties',
            },
        ),
        migrations.AlterModelOptions(
            name='entry',
            options={'verbose_name_plural': 'entries'},
        ),
        migrations.AddField(
            model_name='entry',
            name='main_entry',
            field=models.ForeignKey(blank=True, help_text=b'If this is a sub-entry, link to the parent entry (form without a postbase, for example).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subentries', to='dictionary.Entry'),
        ),
        migrations.AddField(
            model_name='source',
            name='ordering',
            field=models.IntegerField(default=0, help_text=b'Controls what order sources show up in each dictionary entry. Sources with lower values of this number will appear first, with ties broken by alphabetical ordering of the abbreviation.', verbose_name=b'sort location'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='pos',
            field=models.CharField(blank=True, default=b'', help_text=b'To remove the part of speech entirely (show no ending tables for this word), enter "None".', max_length=10, verbose_name=b'part of speech'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='pos_auto',
            field=models.CharField(default=b'None', editable=False, help_text=b'Automatically detected based on the word and other information. If "part of speech" is blank, this will be used.', max_length=10, verbose_name=b'part of speech (guess)'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='root_auto',
            field=models.CharField(default=b'', editable=False, help_text=b'Automatically detected based on the word and other information. If "root" is blank, this will be used.', max_length=100, verbose_name=b'root (guess)'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='source',
            field=models.ForeignKey(blank=True, help_text=b'Dictionary, book, speaker interview, etc. where this word was found', null=True, on_delete=django.db.models.deletion.CASCADE, to='dictionary.Source'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='source_info',
            field=models.CharField(blank=True, default=b'', help_text=b'Page numbers, file IDs, dates, or other specific information needed to find the word in the source.', max_length=200, verbose_name=b'source details'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='source_link',
            field=models.URLField(blank=True, default=b'', help_text=b'A URL to link to the source. If not empty, this will turn the "source details" into a hyperlink.'),
        ),
        migrations.AddField(
            model_name='seealso',
            name='source',
            field=models.ForeignKey(help_text=b'The entry on which this "see also" will appear.', on_delete=django.db.models.deletion.CASCADE, related_name='see_also_outgoing', to='dictionary.Entry'),
        ),
        migrations.AddField(
            model_name='seealso',
            name='target',
            field=models.ForeignKey(help_text=b'The entry this "see also" link will point to. Use the magnifying glass icon to search for entires, then select an entry and its ID will appear here.', on_delete=django.db.models.deletion.CASCADE, related_name='see_also_incoming', to='dictionary.Entry'),
        ),
        migrations.AddField(
            model_name='examplevarietyinfo',
            name='variety',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.Variety'),
        ),
        migrations.AddField(
            model_name='example',
            name='source',
            field=models.ForeignKey(blank=True, help_text=b'Dictionary, book, speaker interview, etc. where this word was found', null=True, on_delete=django.db.models.deletion.CASCADE, to='dictionary.Source'),
        ),
        migrations.AddField(
            model_name='example',
            name='varieties',
            field=models.ManyToManyField(blank=True, help_text=b'Broad language variety, dialect, or geographic region', through='dictionary.ExampleVarietyInfo', to='dictionary.Variety'),
        ),
        migrations.AddField(
            model_name='entryvarietyinfo',
            name='entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.Entry'),
        ),
        migrations.AddField(
            model_name='entryvarietyinfo',
            name='variety',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.Variety'),
        ),
        migrations.AddField(
            model_name='entryexampleinfo',
            name='entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.Entry'),
        ),
        migrations.AddField(
            model_name='entryexampleinfo',
            name='example',
            field=models.ForeignKey(help_text=b'Use the magnifying glass icon to search for or create new examples, then select an example and its ID will appear here.', on_delete=django.db.models.deletion.CASCADE, to='dictionary.Example', verbose_name=b'example ID'),
        ),
        migrations.AddField(
            model_name='entry',
            name='examples',
            field=models.ManyToManyField(blank=True, through='dictionary.EntryExampleInfo', to='dictionary.Example'),
        ),
        migrations.AddField(
            model_name='entry',
            name='see_also',
            field=models.ManyToManyField(blank=True, help_text=b'Other entries that might be useful to look at', related_name='see_also_linked', through='dictionary.SeeAlso', to='dictionary.Entry'),
        ),
        migrations.AddField(
            model_name='entry',
            name='varieties',
            field=models.ManyToManyField(blank=True, help_text=b'Broad language variety, dialect, or geographic region', through='dictionary.EntryVarietyInfo', to='dictionary.Variety'),
        ),
    ]
