# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-20 18:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0003_auto_20180629_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='comments',
            field=models.TextField(default=b'', help_text=b"Usage notes, miscellaneous points of interest, etc. These are visible on the word's page."),
        ),
        migrations.AddField(
            model_name='entry',
            name='etymology',
            field=models.TextField(default=b''),
        ),
        migrations.AddField(
            model_name='entry',
            name='notes',
            field=models.TextField(default=b'', help_text=b"Dictionary maintainers' notes. These are private and only visible to people with access to this admin site."),
        ),
    ]
