# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-03 03:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0004_auto_20190120_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='hidden',
            field=models.BooleanField(default=False, help_text=b'Check this to hide the entry from public viewing (e.g. if it contains things that are sacred, offensive, etc.)'),
        ),
        migrations.AddField(
            model_name='example',
            name='comments',
            field=models.TextField(blank=True, default=b'', help_text=b'Usage notes, miscellaneous points of interest, etc. These are visible below the example.'),
        ),
        migrations.AddField(
            model_name='example',
            name='hidden',
            field=models.BooleanField(default=False, help_text=b'Check this to hide the example from public viewing (e.g. if it contains things that are sacred, offensive, etc.)'),
        ),
        migrations.AddField(
            model_name='example',
            name='notes',
            field=models.TextField(blank=True, default=b'', help_text=b"Dictionary maintainers' notes. These are private and only visible to people with access to this admin site."),
        ),
        migrations.AlterField(
            model_name='entry',
            name='comments',
            field=models.TextField(blank=True, default=b'', help_text=b"Usage notes, miscellaneous points of interest, etc. These are visible on the word's page."),
        ),
        migrations.AlterField(
            model_name='entry',
            name='etymology',
            field=models.TextField(blank=True, default=b''),
        ),
        migrations.AlterField(
            model_name='entry',
            name='notes',
            field=models.TextField(blank=True, default=b'', help_text=b"Dictionary maintainers' notes. These are private and only visible to people with access to this admin site."),
        ),
    ]
