# Generated by Django 3.0.8 on 2020-07-12 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0007_auto_20200712_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='main_entry',
            field=models.ForeignKey(blank=True, help_text='If this is a sub-entry, link to the parent entry (form without a postbase, for example). Use the magnifying glass icon to search for or create new entries, then select an entry and its ID will appear here.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subentries', to='dictionary.Entry'),
        ),
        migrations.AlterField(
            model_name='seealso',
            name='target',
            field=models.ForeignKey(help_text='The entry this "see also" link will point to. Use the magnifying glass icon to search for entries, then select an entry and its ID will appear here.', on_delete=django.db.models.deletion.CASCADE, related_name='see_also_incoming', to='dictionary.Entry'),
        ),
    ]
